{% set name = "exchcxx" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/wavefunction91/ExchCXX/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 0ea38aab563ea5d11a03d80dc1bf909821091d903eb852c5cb350484753a847a

build:
  number: 2
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}
  string: cuda{{ cuda_compiler_version | replace('.', '') }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
  string: cpu_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version == "None"]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [cuda_compiler_version != "None"]
    - {{ stdlib('c') }}
    - cmake
    - ninja
  host:
    - libxc-c >=7,<8
    - cuda-version {{ cuda_compiler_version }}  # [cuda_compiler_version != "None"]

test:
  commands:
    - test -f $PREFIX/lib/libexchcxx$SHLIB_EXT  # [unix]
    - test -f $PREFIX/include/exchcxx/xc_kernel.hpp  # [unix]
    - test -f $PREFIX/lib/cmake/ExchCXX/ExchCXXConfig.cmake  # [unix]

about:
  home: https://github.com/wavefunction91/exchcxx
  summary: 'Exchange correlation (XC) library for density functional theory (DFT) calculations in modern C++'
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - awvwgk
